export type SimulationSeason = "spring" | "summer" | "autumn" | "winter";
export type ShopState = "normal" | "holiday-rush";

export interface CheeseRecord {
  cheeseId: string;
  name: string;
  aliases: string[];
  region: string;
  milkType: "cow" | "goat" | "sheep" | "mixed";
  style: "bloomy rind" | "washed rind" | "blue" | "pressed" | "fresh goat";
  textures: string[];
  pairings: string[];
  servingContexts: string[];
  intensity: number;
  priceEur: number;
  stock: "in" | "low" | "out";
  bestSeasons?: SimulationSeason[];
  seasonalStock?: Partial<Record<SimulationSeason, "in" | "low" | "out">>;
  holidayRushStock?: "in" | "low" | "out";
  blurb: string;
}

export const cheeseCatalog: CheeseRecord[] = [
  {
    cheeseId: "brie-de-meaux",
    name: "Brie de Meaux",
    aliases: ["brie"],
    region: "Ile-de-France",
    milkType: "cow",
    style: "bloomy rind",
    textures: ["creamy", "soft", "buttery"],
    pairings: ["champagne", "baguette", "apple"],
    servingContexts: ["cheese board", "aperitif", "dessert"],
    intensity: 2,
    priceEur: 18,
    stock: "in",
    bestSeasons: ["autumn", "winter"],
    seasonalStock: { summer: "low", winter: "in" },
    holidayRushStock: "low",
    blurb: "Classic bloomy-rind brie with a creamy center and a gentle mushroom note.",
  },
  {
    cheeseId: "camembert-de-normandie",
    name: "Camembert de Normandie",
    aliases: ["camembert"],
    region: "Normandy",
    milkType: "cow",
    style: "bloomy rind",
    textures: ["creamy", "soft", "earthy"],
    pairings: ["cider", "baguette", "pear"],
    servingContexts: ["picnic", "cheese board", "baked"],
    intensity: 3,
    priceEur: 13,
    stock: "in",
    bestSeasons: ["summer", "autumn"],
    seasonalStock: { summer: "in", winter: "in" },
    holidayRushStock: "low",
    blurb: "A softer Normandy cousin to brie with more earth, depth, and cellar character.",
  },
  {
    cheeseId: "chaource",
    name: "Chaource",
    aliases: ["chaource"],
    region: "Champagne",
    milkType: "cow",
    style: "bloomy rind",
    textures: ["creamy", "chalky", "soft"],
    pairings: ["sparkling wine", "hazelnut", "baguette"],
    servingContexts: ["starter", "cheese board"],
    intensity: 2,
    priceEur: 15,
    stock: "low",
    bestSeasons: ["spring", "summer"],
    seasonalStock: { spring: "in", summer: "low", winter: "in" },
    blurb: "Pillowy and lactic, with a creamy paste and a lighter profile than camembert.",
  },
  {
    cheeseId: "epoisses-de-bourgogne",
    name: "Epoisses de Bourgogne",
    aliases: ["epoisses"],
    region: "Burgundy",
    milkType: "cow",
    style: "washed rind",
    textures: ["oozy", "creamy", "spoonable"],
    pairings: ["burgundy", "toasted bread", "pear"],
    servingContexts: ["after dinner", "cheese board"],
    intensity: 5,
    priceEur: 22,
    stock: "in",
    bestSeasons: ["autumn", "winter"],
    seasonalStock: { summer: "low", winter: "in" },
    holidayRushStock: "low",
    blurb: "Very ripe washed-rind cheese that keeps a creamy body while pushing aroma and depth hard.",
  },
  {
    cheeseId: "livarot",
    name: "Livarot",
    aliases: ["livarot"],
    region: "Normandy",
    milkType: "cow",
    style: "washed rind",
    textures: ["supple", "creamy", "dense"],
    pairings: ["cider", "rye bread", "apple"],
    servingContexts: ["cheese board", "pub menu"],
    intensity: 4,
    priceEur: 16,
    stock: "in",
    bestSeasons: ["autumn", "winter"],
    seasonalStock: { summer: "in", winter: "low" },
    holidayRushStock: "out",
    blurb: "A stronger Normandy washed rind that stays balanced and pairs especially well with cider.",
  },
  {
    cheeseId: "munster",
    name: "Munster",
    aliases: ["munster"],
    region: "Alsace",
    milkType: "cow",
    style: "washed rind",
    textures: ["soft", "sticky", "pungent"],
    pairings: ["beer", "potatoes", "cumin"],
    servingContexts: ["warm dish", "cheese board"],
    intensity: 4,
    priceEur: 15,
    stock: "low",
    bestSeasons: ["autumn", "winter"],
    seasonalStock: { winter: "in", summer: "low" },
    holidayRushStock: "low",
    blurb: "A rustic washed rind with a pungent aroma and a fuller, savory finish.",
  },
  {
    cheeseId: "pont-leveque",
    name: "Pont l'Eveque",
    aliases: ["pont leveque", "pont-l'eveque"],
    region: "Normandy",
    milkType: "cow",
    style: "washed rind",
    textures: ["soft", "creamy", "supple"],
    pairings: ["cider", "baguette", "apple"],
    servingContexts: ["cheese board", "aperitif"],
    intensity: 2,
    priceEur: 17,
    stock: "in",
    bestSeasons: ["autumn"],
    seasonalStock: { summer: "low", winter: "low" },
    holidayRushStock: "low",
    blurb: "Normandy washed rind with cider-friendly funk and a gentler profile than livarot.",
  },
  {
    cheeseId: "bleu-dauvergne",
    name: "Bleu d'Auvergne",
    aliases: ["bleu", "blue"],
    region: "Auvergne",
    milkType: "cow",
    style: "blue",
    textures: ["creamy", "crumbly", "salty"],
    pairings: ["dessert wine", "pear", "walnut"],
    servingContexts: ["salad", "cheese board"],
    intensity: 4,
    priceEur: 14,
    stock: "in",
    bestSeasons: ["autumn", "winter"],
    seasonalStock: { autumn: "in", winter: "in", summer: "low" },
    blurb: "Creamy blue cheese with a salty edge and a very different profile from brie.",
  },
  {
    cheeseId: "roquefort",
    name: "Roquefort",
    aliases: ["roquefort"],
    region: "Aveyron",
    milkType: "sheep",
    style: "blue",
    textures: ["creamy", "crumbly", "salty"],
    pairings: ["dessert wine", "pear", "walnut"],
    servingContexts: ["salad", "cheese board", "after dinner"],
    intensity: 5,
    priceEur: 21,
    stock: "in",
    bestSeasons: ["autumn", "winter"],
    seasonalStock: { autumn: "in", winter: "in", summer: "low" },
    holidayRushStock: "low",
    blurb: "Sheep's milk blue with a forceful salty bite for when the vote wants a sharper turn.",
  },
  {
    cheeseId: "crottin-de-chavignol",
    name: "Crottin de Chavignol",
    aliases: ["crottin"],
    region: "Loire",
    milkType: "goat",
    style: "fresh goat",
    textures: ["firm", "chalky", "bright"],
    pairings: ["sancerre", "salad", "baguette"],
    servingContexts: ["starter", "salad"],
    intensity: 3,
    priceEur: 11,
    stock: "in",
    bestSeasons: ["spring", "summer"],
    seasonalStock: { spring: "in", summer: "in", autumn: "low", winter: "out" },
    holidayRushStock: "low",
    blurb: "Goat's milk cheese that brings brightness and tang instead of creamy brie-like richness.",
  },
  {
    cheeseId: "sainte-maure-de-touraine",
    name: "Sainte-Maure de Touraine",
    aliases: ["sainte maure", "sainte-maure"],
    region: "Loire",
    milkType: "goat",
    style: "fresh goat",
    textures: ["chalky", "dense", "bright"],
    pairings: ["sancerre", "baguette", "pear"],
    servingContexts: ["starter", "picnic", "salad"],
    intensity: 3,
    priceEur: 14,
    stock: "in",
    bestSeasons: ["spring", "summer"],
    seasonalStock: { spring: "in", summer: "in", winter: "low" },
    holidayRushStock: "low",
    blurb: "Ash-rinded goat cheese with a chalky center and enough structure for picnic or starter prompts.",
  },
  {
    cheeseId: "valencay",
    name: "Valencay",
    aliases: ["valencay"],
    region: "Loire",
    milkType: "goat",
    style: "fresh goat",
    textures: ["creamy", "chalky", "soft"],
    pairings: ["sancerre", "apple", "baguette"],
    servingContexts: ["starter", "cheese board"],
    intensity: 2,
    priceEur: 16,
    stock: "low",
    bestSeasons: ["spring", "summer"],
    seasonalStock: { spring: "in", summer: "low", winter: "low" },
    blurb: "Pyramid-shaped goat cheese that keeps the goat vote mild, creamy, and easy to compare.",
  },
  {
    cheeseId: "comte-18-mois",
    name: "Comte 18 mois",
    aliases: ["comte"],
    region: "Jura",
    milkType: "cow",
    style: "pressed",
    textures: ["firm", "nutty", "dense"],
    pairings: ["vin jaune", "hazelnut", "baguette"],
    servingContexts: ["snack", "cheese board"],
    intensity: 3,
    priceEur: 19,
    stock: "in",
    bestSeasons: ["autumn", "winter"],
    seasonalStock: { autumn: "in", winter: "in", summer: "low" },
    holidayRushStock: "low",
    blurb: "Aged mountain cheese with nutty depth, but a very different texture from soft-ripened cheeses.",
  },
  {
    cheeseId: "ossau-iraty",
    name: "Ossau-Iraty",
    aliases: ["ossau iraty", "ossau"],
    region: "Basque Country",
    milkType: "sheep",
    style: "pressed",
    textures: ["firm", "nutty", "dense"],
    pairings: ["cherry jam", "beer", "baguette"],
    servingContexts: ["snack", "cheese board", "picnic"],
    intensity: 3,
    priceEur: 18,
    stock: "in",
    bestSeasons: ["summer", "autumn"],
    seasonalStock: { summer: "in", autumn: "in", winter: "low" },
    holidayRushStock: "low",
    blurb: "Firm sheep's milk cheese that gives sheep and pressed-style votes a clean, nutty route.",
  },
  {
    cheeseId: "morbier",
    name: "Morbier",
    aliases: ["morbier"],
    region: "Jura",
    milkType: "cow",
    style: "pressed",
    textures: ["firm", "supple", "nutty"],
    pairings: ["beer", "baguette", "apple"],
    servingContexts: ["snack", "cheese board", "warm dish"],
    intensity: 3,
    priceEur: 15,
    stock: "in",
    bestSeasons: ["autumn", "winter"],
    seasonalStock: { autumn: "in", winter: "in", summer: "low" },
    holidayRushStock: "low",
    blurb: "Supple Jura cheese with a mellow beer-friendly profile for pressed and snack constraints.",
  },
  {
    cheeseId: "tomme-mixte-des-pyrenees",
    name: "Tomme mixte des Pyrenees",
    aliases: ["tomme mixte", "pyrenees tomme"],
    region: "Pyrenees",
    milkType: "mixed",
    style: "pressed",
    textures: ["firm", "nutty", "supple"],
    pairings: ["beer", "cherry jam", "baguette"],
    servingContexts: ["snack", "cheese board", "picnic"],
    intensity: 3,
    priceEur: 17,
    stock: "in",
    bestSeasons: ["summer", "autumn"],
    seasonalStock: { summer: "in", autumn: "in", winter: "low" },
    holidayRushStock: "low",
    blurb: "Mixed-milk mountain tomme that makes the mixed option concrete without overpowering the main brie path.",
  },
];
