export interface CheeseRecord {
  cheeseId: string;
  name: string;
  aliases: string[];
  region: string;
  milkType: "cow" | "goat" | "sheep";
  style: "bloomy rind" | "washed rind" | "blue" | "pressed" | "fresh goat";
  textures: string[];
  pairings: string[];
  servingContexts: string[];
  intensity: number;
  priceEur: number;
  stock: "in" | "low" | "out";
  blurb: string;
}

export const cheeseCatalog: CheeseRecord[] = [
  {
    cheeseId: "brie-de-meaux",
    name: "Brie de Meaux",
    aliases: ["brie"],
    region: "Ile-de-France",
    milkType: "cow",
    style: "bloomy rind",
    textures: ["creamy", "soft", "buttery"],
    pairings: ["champagne", "baguette", "apple"],
    servingContexts: ["cheese board", "aperitif", "dessert"],
    intensity: 2,
    priceEur: 18,
    stock: "in",
    blurb: "Classic bloomy-rind brie with a creamy center and a gentle mushroom note.",
  },
  {
    cheeseId: "camembert-de-normandie",
    name: "Camembert de Normandie",
    aliases: ["camembert"],
    region: "Normandy",
    milkType: "cow",
    style: "bloomy rind",
    textures: ["creamy", "soft", "earthy"],
    pairings: ["cider", "baguette", "pear"],
    servingContexts: ["picnic", "cheese board", "baked"],
    intensity: 3,
    priceEur: 13,
    stock: "in",
    blurb: "A softer Normandy cousin to brie with more earth, depth, and cellar character.",
  },
  {
    cheeseId: "chaource",
    name: "Chaource",
    aliases: ["chaource"],
    region: "Champagne",
    milkType: "cow",
    style: "bloomy rind",
    textures: ["creamy", "chalky", "soft"],
    pairings: ["sparkling wine", "hazelnut", "baguette"],
    servingContexts: ["starter", "cheese board"],
    intensity: 2,
    priceEur: 15,
    stock: "low",
    blurb: "Pillowy and lactic, with a creamy paste and a lighter profile than camembert.",
  },
  {
    cheeseId: "epoisses-de-bourgogne",
    name: "Epoisses de Bourgogne",
    aliases: ["epoisses"],
    region: "Burgundy",
    milkType: "cow",
    style: "washed rind",
    textures: ["oozy", "creamy", "spoonable"],
    pairings: ["burgundy", "toasted bread", "pear"],
    servingContexts: ["after dinner", "cheese board"],
    intensity: 5,
    priceEur: 22,
    stock: "in",
    blurb: "Very ripe washed-rind cheese that keeps a creamy body while pushing aroma and depth hard.",
  },
  {
    cheeseId: "livarot",
    name: "Livarot",
    aliases: ["livarot"],
    region: "Normandy",
    milkType: "cow",
    style: "washed rind",
    textures: ["supple", "creamy", "dense"],
    pairings: ["cider", "rye bread", "apple"],
    servingContexts: ["cheese board", "pub menu"],
    intensity: 4,
    priceEur: 16,
    stock: "in",
    blurb: "A stronger Normandy washed rind that stays balanced and pairs especially well with cider.",
  },
  {
    cheeseId: "munster",
    name: "Munster",
    aliases: ["munster"],
    region: "Alsace",
    milkType: "cow",
    style: "washed rind",
    textures: ["soft", "sticky", "pungent"],
    pairings: ["beer", "potatoes", "cumin"],
    servingContexts: ["warm dish", "cheese board"],
    intensity: 4,
    priceEur: 15,
    stock: "low",
    blurb: "A rustic washed rind with a pungent aroma and a fuller, savory finish.",
  },
  {
    cheeseId: "bleu-dauvergne",
    name: "Bleu d'Auvergne",
    aliases: ["bleu", "blue"],
    region: "Auvergne",
    milkType: "cow",
    style: "blue",
    textures: ["creamy", "crumbly", "salty"],
    pairings: ["dessert wine", "pear", "walnut"],
    servingContexts: ["salad", "cheese board"],
    intensity: 4,
    priceEur: 14,
    stock: "in",
    blurb: "Creamy blue cheese with a salty edge and a very different profile from brie.",
  },
  {
    cheeseId: "crottin-de-chavignol",
    name: "Crottin de Chavignol",
    aliases: ["crottin"],
    region: "Loire",
    milkType: "goat",
    style: "fresh goat",
    textures: ["firm", "chalky", "bright"],
    pairings: ["sancerre", "salad", "baguette"],
    servingContexts: ["starter", "salad"],
    intensity: 3,
    priceEur: 11,
    stock: "in",
    blurb: "Goat's milk cheese that brings brightness and tang instead of creamy brie-like richness.",
  },
  {
    cheeseId: "comte-18-mois",
    name: "Comte 18 mois",
    aliases: ["comte"],
    region: "Jura",
    milkType: "cow",
    style: "pressed",
    textures: ["firm", "nutty", "dense"],
    pairings: ["vin jaune", "hazelnut", "baguette"],
    servingContexts: ["snack", "cheese board"],
    intensity: 3,
    priceEur: 19,
    stock: "in",
    blurb: "Aged mountain cheese with nutty depth, but a very different texture from soft-ripened cheeses.",
  },
];
